Multus images with Ubuntu and Debug option
charmed-kubernetes/charm-multus pull request #12
Opened 2021-04-06 09:44 UTC by phvalguima

Adding the following to multus charm:
* move multus image to Ubuntu as base instead of centos
* debug option: set LogLevel to debug
* multus-debug image which ships multus with delve debugger

2021-04-12 20:21 UTC, Cynerva requested changes
This PR needs integration test coverage. For an example of how to do integration testing in charms, see how we do it in kubernetes-master:

* [test_kubernetes_master_integration.py](https://github.com/charmed-kubernetes/charm-kubernetes-master/blob/master/tests/integration/test_kubernetes_master_integration.py)
* [tox.ini](https://github.com/charmed-kubernetes/charm-kubernetes-master/blob/91e7ae2543db2629504ab6efd9ecac8687396fa0/tox.ini#L21-L28)

2021-04-12 20:21 UTC, Cynerva commented on multus-debug/Dockerfile
> +    git clone https://github.com/k8snetworkplumbingwg/multus-cni /usr/src/multus-cni && \
This git clone needs to pin to a specific tag of the repo, e.g.

```
git clone https://github.com/k8snetworkplumbingwg/multus-cni /usr/src/multus-cni --branch v3.7.1 --depth 1
```

2021-04-12 20:21 UTC, Cynerva commented on multus-debug/Dockerfile
> +ENV INSTALL_PKGS "git golang-1.13 python3 python3-yaml"
It looks like the upstream multus-cni is using golang 1.12, so we should probably do the same:

https://github.com/k8snetworkplumbingwg/multus-cni/blob/v3.7.1/go.mod#L3

2021-04-12 20:21 UTC, Cynerva commented on multus-debug/Dockerfile
> +ENV INSTALL_PKGS "git golang-1.13 python3 python3-yaml"
Nevermind. I tried building with golang 1.12 and encountered this:

```
#8 107.2 # k8s.io/apimachinery/pkg/util/errors
#8 107.2 /go/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/errors/errors.go:99:10: undefined: errors.Is
#8 107.2 note: module requires Go 1.13
```

1.13 it is. Consider adding a comment here to explain why we use 1.13.

2021-04-12 20:21 UTC, Cynerva commented on multus-debug/Dockerfile
> +RUN git clone https://github.com/go-delve/delve && \
This git clone needs to be pinned to a specific tag, e.g.

```
git clone https://github.com/go-delve/delve --branch v1.6.0 --depth 1
```

2021-04-12 20:21 UTC, Cynerva commented on multus/Dockerfile
> +    git clone https://github.com/k8snetworkplumbingwg/multus-cni /usr/src/multus-cni && \
This git clone needs to pin to a specific tag, e.g.

```
git clone https://github.com/k8snetworkplumbingwg/multus-cni /usr/src/multus-cni --branch v3.7.1 --depth 1
```

2021-04-12 20:21 UTC, Cynerva commented on config.yaml
> +      $ dlv attach --continue <PID>
I'm a bit confused about the usage of dlv here. What PID am I supposed to connect to? There is no persistent golang process:

```
$ kubectl exec -n k8s -it multus-jf8h4 -- ps aux
Defaulting container name to kube-multus.
Use 'kubectl describe pod/multus-jf8h4 -n k8s' to see all of the containers in this pod.
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4100  3464 ?        Ss   20:00   0:00 /bin/bash /en
root          57  0.0  0.0   2508   592 ?        S    20:00   0:00 sleep infinit
root          64  0.0  0.0   5888  3068 pts/0    Rs+  20:06   0:00 ps aux
```

2021-04-12 20:21 UTC, Cynerva commented on script/upload
> +URL=$(charm push "$CHARM_BUILD_DIR/$CHARM.charm" "cs:~$NAMESPACE/$CHARM" |  yq -r .url)
This failed for me with yq version 4.6.1:

```
$ NAMESPACE=cynerva make upload
Verifying dependencies...
Error: unknown shorthand flag: 'r' in -r
Usage:
...
Use "yq [command] --help" for more information about a command.

make: *** [Makefile:16: upload] Error 1
```

I think it needs to be:

```
yq eval .url -
```

2021-11-15 17:40 UTC, kwmonroe commented
This PR now conflicts with the main repo and appears to have gone stale wrt requested changes.  I'm closing for now; feel free to reopen if there is still work in progress here.

2021-11-15 17:40 UTC, closed without merging