Convert Multus to the Sidecar pattern
charmed-kubernetes/charm-multus pull request #20
Opened 2022-09-30 00:05 UTC by mateoflorido

## Changes
- Convert the Charm from PodSpec pattern to the Sidecar pattern.

*IMPORTANT: Tests fail in the teardown phase due to a bug in the Juju event handler for Sidecar charms. The `remove` event is not fired, and therefore the resources are not completely cleaned up. Relevant link: [LP#1951415](https://bugs.launchpad.net/juju/+bug/1951415)*

2022-10-04 20:05 UTC, Cynerva requested changes
This is looking good, nice work. I do have some requests and questions, see comments.

2022-10-04 20:05 UTC, Cynerva commented on src/charm.py
> +            return
This generally will not be true for non-leader units, because of the early return in `_install_or_upgrade`, right? Will they just sit in Unknown status forever? I think that could cause problems for the `juju-wait` CLI tool and similar "wait until the model is ready" functions, so I'd probably just put them in Active status if they're not going to do anything.

2022-10-04 20:05 UTC, Cynerva commented on src/charm.py
> +            self.nad_manager.apply_manifests(na_definitions)
What if the `release` config changes? Would we need to re-apply Multus manifests here?

2022-10-04 20:05 UTC, Cynerva commented on src/charm.py
> +        self.manifests.delete_manifests(ignore_unauthorized=True, ignore_not_found=True)
I can't confirm this right now because of the upstream bug, but based on the remove event description [here](https://juju.is/docs/sdk/remove-event), it sounds like the remove event will run on every unit that gets removed. If that's true, then something like:

```
juju add-unit multus
juju remove-unit multus/1
```

could remove Multus and its resources, even though the application still exists with a running unit in Juju. I don't think that's quite what we want.

It's something to investigate further once the Juju bug gets fixed, I suppose.

2022-10-04 20:05 UTC, Cynerva commented on src/manifests.py
> +            ManifestLabel(self),
Should the ConfigRegistry manipulation be in here, too? Without it, the DaemonSet will be applied with an unmodified image field that pulls from ghcr.io, right?

We need the Multus image to come from rocks.canonical.com/cdk by default. I recommend adding an image-registry charm config option to control this.

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +            log.error("Failed reading validation schema")
I think it would be good to log more here - what was the YAMLError exception's message string?

I'm personally a fan of dumping the whole exception with `log.error(traceback.format_exc())`, although I think some people might find that to be too verbose. I'd be happy to at least see the exception's message string.

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +                log.exception(f"Failed applying {rsc}")
Can we log details about the ApiError before we drop it?

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +            return
If this fails, I think we should inform the user in _update_status by putting the charm in Blocked status with a helpful message, or something like that.

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +                log.exception(f"Failed applying {rsc}")
Also, I think we should inform the user that we failed and will retry. Waiting status might be appropriate here.

Actually, will we retry? I think we should - this could be caused by a temporary outage of the Kubernetes API, right?

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +            )
Can we log the ApiError details here?

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +            )
Can we log the ApiError details here?

2022-10-04 20:05 UTC, Cynerva commented on src/net_attach_definitions.py
> +            self.client.delete(type(r.resource), r.name, namespace=r.namespace)
Hmm, is this going to delete every NAD in the cluster that the charm doesn't recognize? What if the user manually created NADs with `kubectl`? Will those get deleted too?

I would be careful not to step on the user experience for NetworkAttachmentDefinitions created via kubectl. The way I handled this before was by having the charm [label every NAD it creates](https://github.com/charmed-kubernetes/charm-multus/blob/15d880711bc117a49c187e49acda01b7316ff53e/net-attach-def-manager/net-attach-def-manager.py#L23) and [only scrub NADs that have that label](https://github.com/charmed-kubernetes/charm-multus/blob/15d880711bc117a49c187e49acda01b7316ff53e/net-attach-def-manager/net-attach-def-manager.py#L41). I think it would be good to do something similar here.

2022-10-11 12:20 UTC, mateoflorido commented
Thanks @Cynerva  for the review. The last commits addressed the previous review.
## Changes
- Non-leader units are set to active status by default.
- Added `image-registry` config option, defaults to `rocks.canonical.com`.
- Increased log verbosity.
- Invalid Network Attachment Definitions YAML now puts the charm in a Blocked State.
- Network Attachment Definitions applied by the charm are now labeled.
- Added `retry` in case the requests fail due to  ApiError exception.

2022-10-11 16:37 UTC, kwmonroe approved these changes
LGTM; i especially like how you centrally handled blocked vs waiting (retrying) event.

2022-10-11 16:39 UTC, merged